@echo off
echo Iniciando ConstructPro...
echo Configurando ambiente de desenvolvimento...
set NODE_ENV=development

echo Verificando dependencias...
call npm install

echo A iniciar servidor...
tsx server/index.ts